openapi: 3.0.4
servers:
  - url: 'https://compras.ds.frre.utn.edu.ar/v1'
info:
  description: >-
    Ejemplo de OAS para Compras.
  version: 1.0.0
  title: OpenAPI Portal de Compras - Desarrollo de Software 2025
  termsOfService: 'http://frre.utn.edu.ar/terminos'
  license:
    name: Apache-2.0
    url: 'https://www.apache.org/licenses/LICENSE-2.0.html'
paths:
  /items:
    get:
      summary: Obtener lista de items
      responses:
        '200':
          description: Lista de items obtenida exitosamente
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                      example: 1
                    name:
                      type: string
                      example: 'Item 1'
        '500':
          description: Error interno del servidor
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: 'Error al obtener la lista de items'